# Generated by Django 5.2.4 on 2025-07-07 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일 (선택)')),
                ('feedback_type', models.CharField(choices=[('feedback', '피드백'), ('term_request', '용어 요청'), ('question', '질문'), ('bug_report', '버그 신고')], default='feedback', max_length=20, verbose_name='유형')),
                ('subject', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음')),
                ('admin_reply', models.TextField(blank=True, verbose_name='관리자 답변')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='답변일')),
            ],
            options={
                'verbose_name': '피드백',
                'verbose_name_plural': '피드백',
                'ordering': ['-created_at'],
            },
        ),
    ]
