# Generated by Django 5.2.4 on 2025-07-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='용어명')),
                ('category', models.CharField(choices=[('basic', '기본 용어'), ('exam', '시험 관련'), ('admission', '입시 전형'), ('score', '성적 관련'), ('university', '대학 관련')], max_length=20, verbose_name='카테고리')),
                ('definition', models.TextField(verbose_name='정의')),
                ('example', models.TextField(blank=True, null=True, verbose_name='예시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_terms', models.ManyToManyField(blank=True, to='terms.term', verbose_name='관련 용어')),
            ],
            options={
                'verbose_name': '입시 용어',
                'verbose_name_plural': '입시 용어들',
                'ordering': ['name'],
            },
        ),
    ]
