# Generated by Django 5.2.4 on 2025-07-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='category',
            field=models.CharField(choices=[('exam', '정시/수시 관련'), ('university', '대학 관련'), ('score', '성적 관련'), ('etc', '기타')], max_length=20, verbose_name='카테고리'),
        ),
    ]
