# Generated by Django 5.2.4 on 2025-07-05 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='대학명')),
                ('type', models.CharField(choices=[('national', '국립대'), ('private', '사립대'), ('specialty', '전문대')], max_length=20, verbose_name='대학 유형')),
                ('region', models.CharField(choices=[('seoul', '서울'), ('gyeonggi', '경기'), ('incheon', '인천'), ('gangwon', '강원'), ('chungbuk', '충북'), ('chungnam', '충남'), ('daejeon', '대전'), ('sejong', '세종'), ('jeonbuk', '전북'), ('jeonnam', '전남'), ('gwangju', '광주'), ('gyeongbuk', '경북'), ('gyeongnam', '경남'), ('daegu', '대구'), ('ulsan', '울산'), ('busan', '부산'), ('jeju', '제주')], max_length=20, verbose_name='지역')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('website', models.URLField(verbose_name='홈페이지')),
                ('established', models.IntegerField(verbose_name='설립연도')),
                ('description', models.TextField(verbose_name='대학 소개')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '대학',
                'verbose_name_plural': '대학들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='학과명')),
                ('college', models.CharField(max_length=100, verbose_name='단과대학')),
                ('description', models.TextField(verbose_name='학과 소개')),
                ('capacity', models.IntegerField(verbose_name='정원')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.university', verbose_name='대학')),
            ],
            options={
                'verbose_name': '학과',
                'verbose_name_plural': '학과들',
                'ordering': ['university', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_type', models.CharField(choices=[('regular', '정시'), ('early', '수시'), ('special', '특별전형')], max_length=20, verbose_name='전형 유형')),
                ('title', models.CharField(max_length=200, verbose_name='전형명')),
                ('description', models.TextField(verbose_name='전형 내용')),
                ('requirements', models.TextField(verbose_name='지원 자격')),
                ('selection_process', models.TextField(verbose_name='선발 방법')),
                ('schedule', models.TextField(verbose_name='일정')),
                ('year', models.IntegerField(verbose_name='학년도')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.university', verbose_name='대학')),
            ],
            options={
                'verbose_name': '입시 정보',
                'verbose_name_plural': '입시 정보들',
                'ordering': ['-year', 'university', 'admission_type'],
            },
        ),
    ]
