# Generated by Django 5.2.4 on 2025-07-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='region',
            field=models.CharField(choices=[('seoul', '서울'), ('gyeonggi', '경기 · 인천'), ('gangwon', '강원'), ('chungbuk', '충북 · 충남 · 대전 · 세종'), ('jeonbuk', '전북 · 전남 · 광주'), ('gyeongbuk', '경북 · 경남 · 부산 · 대구 · 울산'), ('jeju', '제주')], max_length=20, verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='university',
            name='type',
            field=models.CharField(choices=[('national', '국 · 공립대'), ('private', '사립대')], max_length=20, verbose_name='대학 유형'),
        ),
    ]
